name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
        stable-features:
          - ""
          - "default"
          - "derive"
          - "std"
          - "via_default_eq"
          - "default,via_default_eq"

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - run: cargo test --verbose --no-default-features --features "${{ matrix['stable-features'] }}"
      - run: cargo test --verbose --no-default-features --features "${{ matrix['stable-features'] }}" --release

      - if: matrix.toolchain == 'stable' && matrix.stable-features == ''
        name: Build no_std only target
        run: |
          rustup target add x86_64-unknown-none
          cargo build --verbose --no-default-features --target x86_64-unknown-none
          cargo build --verbose --no-default-features --target x86_64-unknown-none --release

      - if: matrix.toolchain == 'nightly'
        run: |
          cargo test --verbose --no-default-features --features "${{ matrix['stable-features'] }},nightly"
          cargo test --verbose --no-default-features --features "${{ matrix['stable-features'] }},nightly" --release
